gfx/env/nightsky_bk.tga
gfx/env/nightsky_dn.tga
gfx/env/nightsky_ft.tga
gfx/env/nightsky_lf.tga
gfx/env/nightsky_rt.tga
gfx/env/nightsky_up.tga
models/ng_re_piola.mdl
sound/zm_ngamers_lights/quetocas.wav
sound/zm_ngamers_lights/elrayo.wav
maps/zm_ngamers_lights_f.res
maps/zm_ngamers_lights_f.txt
