//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_zero_blood.html
halflife.wad
decals.wad
cstrike.wad
cs_dust.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
maps/zm_zero_blood.bsp
